api_platform:
    title: 'CRM API'
    description: 'API Symfony 5 for Customer Relationship Management'
    version: '0.1.0'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            enabled: false
            enabled_parameter_name: 'paginate'
            items_per_page: 10
            client_enabled: true
            client_items_per_page: true
            page_parameter_name: 'page'
            items_per_page_parameter_name: 'count'
